### PR TITLE
Add more icons for the light and dark variant of the theme

### PR DESCRIPTION
**Pull request by bogdancernat**
I just wanted to add the Vue icon but ended up adding more icons from a different theme that I had installed.

### CODE REVIEW

**Comment by tomm1996** [comment]
@bogdancernat  have you tested this for all icons? I do not see the icons with the latest build.
image

**Comment by bogdancernat** [comment]
@tomm1996 Hey! I'm up to date with the repository on my laptop and I can see my added icons.

image

**Comment by tomm1996** [comment]
@bogdancernat  I tested it with a fresh install on another machine and some icons still are not loaded for some reason. What OS are you working on? Also, do you have any relevant packages like [A File Icon](https://github.com/ihodev/a-file-icon) installed?

**Comment by bogdancernat** [comment]
@tomm1996 No, I don't have that package installed. Running on macOS Sierra. Also, the branch where I made the changes is 'more-icons' not master if that helps for some reason.

**Comment by tomm1996** [comment]
@bogdancernat Well, I tried both, the master from the original repo and your more-icons branch (on two different Windows 10 machines). For some reason, several files such as scss and less files just show the cogwheel as fallback. I upgraded to the dev build of ST3 but it didn't make a difference. I doubt it's an issue with your PR. I will look into this but until then I can't really review your PR.

**Pull request merged**
