### PR TITLE
Fix PHP sidebar icon context: from source.php to embedded.php

### PR DESCRIPTION
**Pull request by jobedom**
Generic cog icon for PHP files in the sidebar, which is not correct. The proper context for such files in the icon definition is `embedding.php`. Even when Sublime shows `source.php` as one of the contexts for PHP sources, it seems themes sidebar icons only take first context into account (`embedding.php`).

### CODE REVIEW

**Comment by jobedom** [comment]
Please, wait for this PR again in a few hours. I have to clean up my fork and my local repo (something strange happened).

**Comment by jobedom** [comment]
I think it's ok. Please tell me if you see something wrong.

**Comment by michael-jahn-dev** [comment]
Hm okay, I'll review this the next days. Currently I'm a bit busy.

**Comment by michael-jahn-dev** [comment]
@jobedom Well, I don't have the issue seeing a generic cog icon in my sidebar for php files. Everything seems fine for me. Are you sure this is a bug in the theme itself or maybe with your installation?

image

**Comment by jobedom** [comment]
I'm checking it, Miw0. I think the only difference from a fresh installed Sublime that could affect PHP scoping could be [PHP Modern](https://github.com/jobedom/sublime-php-modern), a package of my own, so I'll investigate my own installation. Thanks!

**Pull request closed without merging**
